SEED: 42

PATH:
  data: data
  viz: figures
  model: model
  logs: logs

data:
  train_test_split: 0.1
  NUM_COLS:
    - tenure
    - MonthlyCharges
    - TotalCharges
  CAT_COLS_OHE:
    - PaymentMethod
    - Contract
    - InternetService
  CAT_COLS_OE:
    - OnlineSecurity
    - MultipleLines
    - Dependents
    - DeviceProtection
    - StreamingTV
    - OnlineBackup
    - gender
    - SeniorCitizen
    - PhoneService
    - Partner
    - PaperlessBilling
    - StreamingMovies
    - TechSupport

model:
  n_trials: 100
  models:
    dummy:
    knn:
    lr:
    svm:
    rf:
    gb:
    dt:
    abc:
    voting:
    - gb
    - lr
    - abc
    xgb: