# DEV: Add conf variables
SEED: 42

PATH:
  data: data
  viz: figures
  model: models
  logs: logs

data:
  load:
    strategy: dir
    args:
      dir: data
      columns:
        - customerID
        - gender
        - SeniorCitizen
        - Partner
        - Dependents
        - tenure
        - PhoneService
        - MultipleLines
        - InternetService
        - OnlineSecurity
        - OnlineBackup
        - DeviceProtection
        - TechSupport
        - StreamingTV
        - Contract
        - PaperlessBilling
        - PaymentMethod
        - MonthlyCharges
        - TotalCharges
        - Churn
  split:
    ratio: 0.1
    stratify: True
  train_test_split: 0.1
  NUM_COLS:
    - tenure
    - MonthlyCharges
    - TotalCharges
  CAT_COLS_OHE:
    - PaymentMethod
    - Contract
    - InternetService
  CAT_COLS_OE:
    - OnlineSecurity
    - MultipleLines
    - Dependents
    - DeviceProtection
    - StreamingTV
    - OnlineBackup
    - gender
    - SeniorCitizen
    - PhoneService
    - Partner
    - PaperlessBilling
    - StreamingMovies
    - TechSupport

model:
  n_trials: 2
  models:
    dummy:
    lr:
    svm:
    rf:
    gb:
    dt:
    abc:
    voting:
      - gb
      - lr
      - abc
    xgb:
