name: Deploy

on: workflow_dispatch

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.CHURNOBYL_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CHURNOBYL_SECRET_KEY }}
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"
      - name: Install dependancies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup Wandb and Prefect
        shell: bash
        env:
          WANDB_API: ${{ secrets.WANDB_KEY }}
          API_KEY: ${{ secrets.PREFECT_API_KEY_CHURNOBYL }}
        run: |
          wandb login "$WANDB_API"
          echo "Wandb login successful"
          prefect cloud login -k $API_KEY --workspace ishandandekar/churnobyl
