name: Tests
on:
  schedule:
    - cron: "0 0 2 * *"
  workflow_dispatch:
  # push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"
      - name: Install dependancies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
